llm_inference:
  workflow_type: "load_podcasts_from_marketplace"
  url: "https://www.marketplace.org/feed/podcast/marketplace/" 
  file_type: "audio/mpeg"
  max_download: 20 
  episode_file_db: "./podcast_file_db"
  episode_folder: "./audio/podcasts"
