llm_inference:
  workflow_type: "chat_rag_with_podcasts"

  model:
    name: "llama2-uncensored:latest"
    device: "cpu"
    temperature: 0.5 
    max_tokens: 100

  rag:
    vector_store: "chromadb"
    vector_store_path: "./chromadb"
    vector_store_collection: "summaries_marketplace_podcasts"
    vector_store_embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
    vector_store_hnsw_search_algo: "cosine"
    chunk_size: 2000
    chunk_overlap: 100

  chat:
    format_color_of_response: "CYAN"
    console_line_length: 100
    prompt_template: >
      Use the following pieces of context to answer the question at the end.
      If you don't know the answer, just say that you don't know, don't try to make up an answer.
      Use five sentences maximum and keep the answer as concise as possible.
      {context}
      Question: {question}
      Helpful Answer:

  processing:
    episode_folder: "./audio/podcasts"
    speaker_output_action: "./src/audio_output.sh"
    speaker_output_voice:  "female_03.wav"

