llm_inference:
  workflow_type: "chat_rag_with_pdf"

  model:
    name: "llama2-uncensored:latest"
    device: "cpu"
    temperature: 0.5 
    max_tokens: 100

  rag:
    vector_store: "chromadb"
    vector_store_path: "/usr/app/ollama/chromadb"
    vector_store_collection: "book_game_of_thrones"
    vectore_store_embedding_model: "sentence-transformers/all-mpnet-base-v2"
    chunk_size: 1000
    chunk_overlap: 50
    pdf: "/usr/app/ollama/pdf/game_of_thrones/A_Game_Of_Thrones.pdf" 

  chat:
    prompt_template: >
      Use the following pieces of context to answer the question at the end.
      If you don't know the answer, just say that you don't know, don't try to make up an answer.
      Use five sentences maximum and keep the answer as concise as possible.
      {context}
      Question: {question}
      Helpful Answer:
