FROM python:3.11-bookworm

WORKDIR /usr/app/ollama

RUN apt-get update -y \
    && apt-get install -y vim \
    && apt-get install -y systemd \
    && mkdir src \
    && mkdir chromadb \
    && mkdir -p pdf/game_of_thrones \
    && mkdir pdf/amd \
    && mkdir pdf/cloudera \
    && curl -fsSL https://ollama.com/install.sh | sh

COPY --chmod=755 requirements.txt ./
COPY --chmod=755 config_chat_pdf.yml ./
COPY --chmod=755 src/chat_with_rag_pdf.py ./src
COPY --chmod=755 src/main.py ./src
COPY --chmod=755 src/parse_yaml.py ./src
COPY --chmod=755 src/suppress_std_out.py ./src
COPY --chmod=755 pdf/game_of_thrones/A_Game_Of_Thrones.pdf ./pdf/game_of_thrones

RUN pip install -r ./requirements.txt

#RUN ollama serve >> logs/ollama-log.txt 2>&1 &
#RUN ollama pull llama2-uncensored:latest 
#RUN ollama pull llama3
